### ISSUE TITLE
Create Penerimaan Otomatis Ketika SO

### ISSUE THREAD

**Issue by NandaArapenta** [agussustian2017/RSAB_Harapan_Kita#113]

**Comment by evanandrian** [comment]
[https://app.zenhub.com/files/135328973/ef61da0b-c9fb-47eb-ba99-e8e48f0c18bf/download](https://app.zenhub.com/files/135328973/ef61da0b-c9fb-47eb-ba99-e8e48f0c18bf/download)

file txt, format nama harus sama (SO_tglso(yyyy-mm-dd)_kdruangan_namaruangan.txt)
