### ISSUE TITLE
Tambah Nama Penjamin

### ISSUE THREAD

**Issue by agussustian2017** [agussustian2017/RSAB_Harapan_Kita#162]
Nama Penjamin kalau dia Pasien Perusahaan/Asuransi biar bisa di acc pihak penjamin

![WhatsApp Image 2018-06-30 at 11.05.57 AM.jpeg](https://images.zenhubusercontent.com/5b0d8a44cca077261f801daa/3315433c-6cd1-4940-9b94-be318c285b27)

**Comment by ramdanegie** [comment]
Update @NandaArapenta 

FrontEnd ->
app\module\Penunjang\RegistrasiPenunjang.html
app\module\Penunjang\RegistrasiPenunjangCtrl.js

BackEnd ->
app\Http\Controllers\Transaksi\Pelayanan\PasienController.php
