### ISSUE TITLE
Form Setoran Kasir + Cetakan

### ISSUE THREAD

**Issue by agussustian2017** [agussustian2017/RSAB_Harapan_Kita#58]

**Comment by ramdanegie** [comment]
*FRONT
app/data/GetRequireConfigAkuntansi.json
app/data/GetRoutingAkuntansi.json
app/data/GetSideMenu/bendaharaPenerimaan.json
app/javascripts/Services/Akuntansi/PhpServices.js
app/module/Akuntansi/BendaharaPenerimaan/SetoranKasirPHP.html
app/module/Akuntansi/BendaharaPenerimaan/SetoranKasirPHPCtrl.js
app/module/AplikasiIT/DataMaster/CaraSetor.html
app/module/AplikasiIT/DataMaster/CaraSetorCtrl.js

*BACK
app/Http/routes.php
app/Http/Controllers/Transaksi/Kasir/SetoranKasirController.php
app/Master/CaraSetor.php
