### ISSUE TITLE
Form History Rekening Koran

### ISSUE THREAD

**Issue by agussustian2017** [agussustian2017/RSAB_Harapan_Kita#59]

**Comment by ramdanegie** [comment]
*BACK
app\Http\Controllers\Transaksi\BendaharaPenerimaan\PenerimaanBankController.php

*FRONT
app/data/GetRoutingAkuntansi.json
app/module/Akuntansi/BendaharaPenerimaan/MonitoringRekeningKoranBendaharaPenerimaan.html
app/module/Akuntansi/BendaharaPenerimaan/MonitoringRekeningKoranBendaharaPenerimaanCtrl.js
